version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/e2e.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - demo-server
      - demo-front-end
    networks:
      - backend
      - frontend

  demo-server:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - backend
      - frontend

  demo-front-end:
    build:
      context: ./front-end-demo
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./front-end-demo:/app
      - node-module-cache:/app/node_modules
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - demo-server
    networks:
      - frontend

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  gradle-cache:
  node-module-cache:
