version: '3.1'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8000:8000
      - 443:443
    volumes:
      - ../nginx/demo.conf:/etc/nginx/demo.conf
    depends_on:
      - app
  app:
    container_name: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb