version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ../nginx/backend.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - demo-server
  demo-server:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
